apiVersion: v1
kind: Service
metadata:
  namespace: fastapi-dev
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
