name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Upload Kubernetes YAML to VPS
        run: |
          scp -o StrictHostKeyChecking=no fastapi-deployment.yaml fastapi-service.yaml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/deploy/app/

      - name: Deploy via kubectl on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/deploy/app
            microk8s kubectl apply -f fastapi-deployment.yaml
            microk8s kubectl apply -f fastapi-service.yaml

            DEPLOY_NAME=fastapi-hello
            NAMESPACE=default

            echo "🔍 Checking if deployment exists..."
            if microk8s kubectl get deployment $DEPLOY_NAME -n $NAMESPACE > /dev/null 2>&1; then
              echo "✅ Restarting deployment $DEPLOY_NAME"
              microk8s kubectl rollout restart deployment $DEPLOY_NAME -n $NAMESPACE
            else
              echo "ℹ️ Deployment $DEPLOY_NAME not found, probably first-time deploy."
            fi
          EOF
